import os

STORAGE_ACCOUNT_NAME = "sensoranalytics"

STORAGE_ACCOUNT_KEY = os.environ.get("STORAGE_ACCOUNT_KEY")
AZCOPY_ACCOUNT_KEY=os.environ.get("STORAGE_ACCOUNT_KEY")

CONTAINER_NAME = "landing"
AZURE_CONNECTION_STRING = os.environ["AZURE_CONNECTION_STRING"]

